# -*- coding: utf-8 -*-
"""modelling.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NeH6WFvHAoJk7g38GMSKsjdYaZLssIIH
"""

import pandas as pd
import matplotlib.pyplot as plt
import os
import shutil
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
import mlflow
import mlflow.sklearn

# Hapus folder saved_model jika sudah ada sebelumnya
if os.path.exists("saved_model"):
    shutil.rmtree("saved_model")

# Membaca dataset
df = pd.read_csv('sample_data/heart_preprocessing.csv')
X = df.drop('HeartDisease', axis=1)
y = df['HeartDisease']

# Membagi data latih dan uji
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Memulai tracking MLflow
with mlflow.start_run():
    rf = RandomForestClassifier(n_estimators=50, random_state=42)
    rf.fit(X_train, y_train)

    y_pred = rf.predict(X_test)
    acc = accuracy_score(y_test, y_pred)
    mlflow.log_metric("accuracy", acc)

    # Simpan artefak sederhana berupa gambar akurasi
    plt.figure(figsize=(4,3))
    plt.text(0.5, 0.5, f'Akurasi Model: {acc:.2f}', ha='center', va='center')
    plt.axis('off')
    plt.savefig("akurasi.png")
    mlflow.log_artifact("akurasi.png")

    # Menyimpan model untuk Docker (Ini bagian paling penting untuk CI!)
    mlflow.sklearn.log_model(rf, "model")
    mlflow.sklearn.save_model(rf, "saved_model")